force-app/main/default/objects/Species__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoors</fullName>
                <default>true</default>
                <label>Indoors</label>
            </value>
            <value>
                <fullName>Outdoors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpeciesService.cls
public with sharing class SpeciesService {
    @AuraEnabled(cacheable = true)
    public static List<Species__c> getFilteredSpecies(String speciesSearchesText) {

        String likeValue = '%' + speciesSearchesText + '%';

        return [
            SELECT Id, Name, Description__c, Image_URL__c, Location__c
            FROM Species__c
            WHERE Name
            LIKE :likeValue
        ];
    }
}